package com.superredrock.usbthief.gui.dailog.filter;

import com.superredrock.usbthief.gui.I18nManager;

import javax.swing.JLabel;
import javax.swing.JSlider;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.List;
import java.util.Locale;

/**
 * Slider ranges, unit mappings and the slider factory shared by the filter
 * settings pages.
 *
 * <p>Extracted from {@code FilterConfigDialog} (architecture-audit [19]). The
 * value mapping from wire names ({@code "HOURS"}) to display indices used to be
 * spread over three switch expressions; it now has a single home.</p>
 */
final class FilterRanges {

    private static final I18nManager i18n = I18nManager.getInstance();

    /** Time unit ranges: [min, max, majorTick, minorTick, labelStep]. */
    static final int[][] TIME_RANGES = {
        {1, 168, 24, 6, 48},   // HOURS: 1小时 - 1周, 标签: 1, 48, 96, 144, 168
        {1, 90, 15, 5, 30},    // DAYS: 1天 - 3个月, 标签: 1, 30, 60, 90
        {1, 52, 10, 2, 13},    // WEEKS: 1周 - 1年, 标签: 1, 13, 26, 39, 52
        {1, 36, 6, 1, 12},     // MONTHS: 1月 - 3年, 标签: 1, 12, 24, 36
        {1, 10, 2, 1, 3}       // YEARS: 1年 - 10年, 标签: 1, 3, 6, 9, 10
    };

    /** Size unit ranges: [min, max, labelStep]. */
    static final int[][] SIZE_RANGES = {
        {1, 1000, 250},  // MB: 标签 1, 250, 500, 750, 1000
        {1, 100, 25}     // GB: 标签 1, 25, 50, 75, 100
    };

    /** Size unit multipliers (to bytes). */
    static final long[] SIZE_MULTIPLIERS = {
        1024 * 1024,        // MB
        1024L * 1024 * 1024 // GB
    };

    /** Wire names of the time units, indexed by combo box index. */
    private static final String[] TIME_UNIT_NAMES =
        {"HOURS", "DAYS", "WEEKS", "MONTHS", "YEARS"};

    /** Short unit suffix i18n keys, indexed by combo box index. */
    private static final String[] TIME_UNIT_SUFFIX_KEYS = {
        "filter.slider.unit.hours",
        "filter.slider.unit.days",
        "filter.slider.unit.weeks",
        "filter.slider.unit.months",
        "filter.slider.unit.years"
    };

    private FilterRanges() {
    }

    /**
     * Creates a styled JSlider with labels.
     */
    static JSlider createSlider(int min, int max, int value, int majorTick, int minorTick,
                                int labelStep, String unitSuffix) {
        JSlider slider = new JSlider(min, max, value);
        slider.setMajorTickSpacing(majorTick);
        slider.setMinorTickSpacing(minorTick);
        slider.setPaintTicks(true);
        slider.setPaintLabels(true);
        updateSliderLabels(slider, min, max, labelStep, unitSuffix);
        return slider;
    }

    /**
     * Rebuilds the slider label table (UI-05).
     *
     * <p>The previous implementation placed the last intermediate label at
     * {@code max - (max % labelStep)}, which for the 1..168 hour range put "144"
     * only 24 units away from the "168" end label. The two labels visually merged
     * into the bogus reading "144168". Labels are now generated by walking down
     * from {@code max} in even {@code labelStep} steps, so the spacing is uniform
     * and the maximum is always labelled; the minimum is only added when there is
     * room for it. Each label carries a short unit suffix so the numbers are
     * self-explanatory.</p>
     */
    static void updateSliderLabels(JSlider slider, int min, int max, int labelStep, String unitSuffix) {
        Dictionary<Integer, JLabel> labelTable = new Hashtable<>();
        String suffix = unitSuffix == null ? "" : unitSuffix;
        int step = Math.max(1, labelStep);

        List<Integer> positions = new ArrayList<>();
        for (int value = max; value >= min; value -= step) {
            positions.add(0, value);
            if (value - step < min) {
                break;
            }
        }

        // Add the minimum only when it is far enough from the first label to be readable
        int first = positions.get(0);
        if (first > min && (first - min) >= step / 2) {
            positions.add(0, min);
        }

        for (int value : positions) {
            labelTable.put(value, new JLabel(value + suffix));
        }

        slider.setLabelTable(labelTable);
    }

    /**
     * Combo box index of a time unit wire name, defaulting to hours.
     */
    static int timeUnitIndex(String unitName) {
        if (unitName == null) {
            return 0;
        }
        String normalized = unitName.toUpperCase(Locale.ROOT);
        for (int i = 0; i < TIME_UNIT_NAMES.length; i++) {
            if (TIME_UNIT_NAMES[i].equals(normalized)) {
                return i;
            }
        }
        return 0;
    }

    /**
     * Time unit wire name for a combo box index, defaulting to hours.
     */
    static String timeUnitName(int index) {
        if (index < 0 || index >= TIME_UNIT_NAMES.length) {
            return TIME_UNIT_NAMES[0];
        }
        return TIME_UNIT_NAMES[index];
    }

    /**
     * Short unit suffix used on the time slider labels; empty when the bundle has
     * no translation for that unit.
     */
    static String timeUnitSuffix(int index) {
        String key = TIME_UNIT_SUFFIX_KEYS[
            (index < 0 || index >= TIME_UNIT_SUFFIX_KEYS.length) ? 0 : index];
        String value = i18n.getMessage(key);
        return value.startsWith("!") ? "" : value;
    }
}
